### ISSUE TITLE
Issue opening notes

### ISSUE THREAD

**Issue by andreshazard** [mrtazz/simplenote.vim#81] opened 2016-04-20 21:42 UTC
I'm having issues opening any note FYI. 

> Error detected while processing function <SNR>53_GetNoteToCurrentBuffer:
> line    3:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "<string>", line 287, in display_note_in_scratch_buffer
>   File "<string>", line 32, in set_current_note
> vim.error: Vim(file):E16: Invalid range

My vim version has python enabled : 

+python/dyn
+python3/dyn

am I missing something ? 

Thanks for this awesome plugin!

**Comment by jonbartlett** [comment] 2016-04-21 00:46
I am getting the same error when opening selective notes:

`"SN_VIM_notes" [New File]
Error detected while processing function <SNR>95_GetNoteToCurrentBuffer:
line    3:
E16: Invalid range
"SN_VIM_notes [agtzaW1wbGUtbm90ZXINCxIETm90ZRiJk-IHDA]" [Not edited][New file] --No lines in buffer--
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 287, in display_note_in_scratch_buffer
  File "<string>", line 32, in set_current_note
vim.error`

**Comment by atomicules** [comment] 2016-04-21 19:34
Thanks for letting me know. I will investigate and get back to you.

**Comment by atomicules** [comment] 2016-04-21 22:30
I've just had a quick look for now and unfortunately can't reproduce the problem. I tried with my normal simplenote.vim configuration and with the default one. I'll have to spend more time investigating it this weekend.

**Comment by andreshazard** [comment] 2016-04-21 22:33
@atomicules Let me know if I can help in any way. 
Maybe add as a collaborator on the note I'm trying to open or something.

**Comment by atomicules** [comment] 2016-04-21 22:33
If either of you have the chance and are able to, I'd be interested to see if you face the same issues with a previous version. I.e version 1.0.0.

**Comment by atomicules** [comment] 2016-04-21 22:35
I started trying to make things a bit more clever internally at version 1.1.0 (hence why there have been a few point releases). I'm thinking there might be an issue there I've not come across myself yet.

**Comment by andreshazard** [comment] 2016-04-21 22:43
Sure, let me know how to downgrade to the version 1.0.0

**Comment by atomicules** [comment] 2016-04-21 23:02
@andreshazard How have you installed simplenote.vim? I'm assuming it's via one of the plugin managers. If so you could git checkout the v1.0.0 tag in the bundle directory. I can provide clearer instructions tomorrow (Friday). I've got dash for now unfortunately.

**Comment by andreshazard** [comment] 2016-04-21 23:36
@atomicules I did the checkout and is now  working. Thanks

**Comment by atomicules** [comment] 2016-04-22 08:01
Ok, thanks for doing that. That gives me something to work on in figuring out what's broken at 1.1.X

**Comment by atomicules** [comment] 2016-04-22 08:06
@andreshazard and @jonbartlett What version of Vim are you using, out of interest? Also, what operating system?

**Comment by atomicules** [comment] 2016-04-22 08:14
Notes to self:

Problem seems to be this bit of code in `set_current_note`:

    vim.command(""" silent exe "file %s [%s]" """ % (buffertitle,note_id))

For comparison, at version 1.0.0 the equivalent was:

    vim.command(""" silent exe "file %s" """ % buffertitle)

The E16 error isn't too helpful. Having a quick search it could be related to the vim version or it could be to do with the vim regex engine selected (although hard to see how that would come into play here).

**Comment by andreshazard** [comment] 2016-04-22 13:24
@atomicules 
_VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 14:13:25)_

I'm using Fedora 23. 

Let me know if you need anything else

**Comment by atomicules** [comment] 2016-04-22 14:10
@andreshazard Which patch version? I.e mine is 7.4.1040

**Comment by andreshazard** [comment] 2016-04-22 14:53
@atomicules  For what I see the :version I have _1-1718_
Here is the complete output : 

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 14:13:25)
Included patches: 1-1718
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +libcall         +mouse_dec       +netbeans_intg   +reltime         +tag_old_static  +virtualedit     -xim
+arabic          +cmdline_hist    -dnd             -footer          +linebreak       +mouse_gpm       +packages        +rightleft       -tag_any_white   +visual          -xsmp
+autocmd         +cmdline_info    -ebcdic          +fork()          +lispindent      -mouse_jsbterm   +path_extra      +ruby/dyn        -tcl             +visualextra     -xterm_clipboard
-balloon_eval    +comments        +emacs_tags      +gettext         +listcmds        +mouse_netterm   +perl            +scrollbind      +terminfo        +viminfo         -xterm_save
-browse          +conceal         +eval            -hangul_input    +localmap        +mouse_sgr       +persistent_undo +signs           +termresponse    +vreplace        -xpm
++builtin_terms  +cryptv          +ex_extra        +iconv           +lua/dyn         -mouse_sysmouse  +postscript      +smartindent     +textobjects     +wildignore
+byte_offset     +cscope          +extra_search    +insert_expand   +menu            +mouse_urxvt     +printer         +startuptime     +timers          +wildmenu
+channel         +cursorbind      +farsi           +job             +mksession       +mouse_xterm     +profile         +statusline      +title           +windows
+cindent         +cursorshape     +file_in_path    +jumplist        +modify_fname    +multi_byte      +python/dyn      -sun_workshop    -toolbar         +writebackup
-clientserver    +dialog_con      +find_in_path    +keymap          +mouse           +multi_lang      +python3/dyn     +syntax          +user_commands   -X11
-clipboard       +diff            +float           +langmap         -mouseshape      -mzscheme        +quickfix        +tag_binary      +vertsplit       -xfontset
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/u
sr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro   -Wl,-z,relro -specs=/usr/l
ib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro  -Wl,-z,relro
-fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -lnsl -ldl -lm -lcrypt -lutil -lc

Let me know if this is not what you were you were looking for.

**Comment by atomicules** [comment] 2016-04-22 14:55
Thanks. Yeah the `1-1718` is enough for me to figure out if the error is due to a patch changes in Vim.

**Comment by atomicules** [comment] 2016-04-22 19:45
I'm trying to build a more recent version on NetBSD so I can investigate whether the patch level is the issue or not.

**Comment by atomicules** [comment] 2016-04-22 22:00
I've just built and tested with patch version 1778 and briefest of testing showed it to be ok. I'll also build 1718 to check.

**Comment by atomicules** [comment] 2016-04-22 22:57
Ok, tried 1718 and also works fine so it's unlikely to be a patch level issue. Also tried setting `regexpengine` to `1` and `2` and both work for me so this is getting tricky.

I think I'll have to get a Fedora instance running to check.

**Comment by atomicules** [comment] 2016-04-22 23:05
Also tried with the Windows 7.4 release and no problems there either.

@andreshazard Were you definitely seeing this issue on all notes?

**Comment by atomicules** [comment] 2016-04-23 00:00
Ok, this is driving me slightly insane now. I spun up a Fedora 22 (23 wasn't readily available) and used the default vim 7.4.640 and I can still open all of my notes that I tried with.

I wonder if there are some settings in your vimrc that are causing a conflict or something?

@jonbartlett I'd really appreciate it if you could also let me know your operating system, version of Vim, etc.

**Comment by andreshazard** [comment] 2016-04-23 14:07
@atomicules I was getting the error on all notes, even new blank notes. 
You can test with my vimrc, is on my dotfiles. 
Let me know if I can so something

**Comment by atomicules** [comment] 2016-04-23 14:08
Thanks, I'll have a go with your vimrc and see if that sheds any light.

**Comment by atomicules** [comment] 2016-04-23 14:19
@andreshazard Just tested with your vimrc (and also installed the other plugins you use) and no issue.

This is a strange one.

**Comment by andreshazard** [comment] 2016-04-23 17:13
It really is @atomicules Let me know if I can help with some testing.

**Comment by atomicules** [comment] 2016-04-24 00:03
@andreshazard Thanks for working with me on this. I've just pushed a new branch. You should be able to do a `git fetch --all` and then a `git checkout --track origin/issue81` within the bundle directory like you did to get version v1.0.0. Could you please try that and see if that works?

**Comment by andreshazard** [comment] 2016-04-24 03:05
It works @atomicules  =)

**Comment by atomicules** [comment] 2016-04-24 10:24
Yay! That's great news @andreshazard. Thanks for testing.

I'll merge this into master and make a new release.

Within the bundle directory you should do a `git checkout master` and then you can run Vundle's `BundleUpdate`.

@jonbartlett I'll close this, but feel free to re-open if it hasn't also fixed it for you.

**Closed by atomicules** 2016-04-24 10:24 UTC
Labels: bug
