### ISSUE TITLE
Support for vim8 async

### ISSUE THREAD

**Issue by kiryph** [mrtazz/simplenote.vim#88] opened 2016-09-08 15:38 UTC
vim8 will be released very soon (http://www.vim.org/). So it also would be great to have async support for vim8 not only for neovim.

**Comment by atomicules** [comment] 2016-09-08 15:51
Thanks for the heads up.

**Comment by atomicules** [comment] 2016-09-21 15:40
Waiting on vim8 for NetBSD/Pkgsrc.

**Comment by atomicules** [comment] 2016-10-06 22:03
Closing as a duplicate of #66 because that was here first.

**Closed by atomicules** 2016-10-06 22:03 UTC
Labels: duplicate, harder
